### ISSUE TITLE
Falta un Vengador en la lista de miembros

### ISSUE THREAD

**Issue by GranadaDavid** [GranadaDavid/Vengadores#1]
### Falta un Vengador

Por favor, agregad a Nick Fury

**Comment by ivana0312** [comment]
Falta otro vengador Profe

**Comment by GranadaDavid** [comment]
Nick Fury NO es un Vengador.

**Comment by GranadaDavid** [comment]
Nick Fury SÍ que es un Vengador, agregadlo a la lista.

**Comment by GranadaDavid** [comment]
Oye jefe, el problema se resolvió aquí: 5aeaa78
